=== exadmin/qubership-inventory-tool-cli/docs/application_inventory_schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "description": "Application id in form 'application:${name}:${version}",
      "type": "string"
    },
    "name": {
      "description": "Application name",
      "type": "string"
    },
    "version": {
      "description": "Application version",
      "type": "string"
    },
    "components": {
      "description": "Components in this application. Components are usually microservices",
      "type": "array",
      "items" : {
        "type": "object",
        "properties": {
          "id": {
            "description": "Component id",
            "type": "string"
          },
          "name": {
            "description": "Component name",
            "type": "string"
          },
          "owner": {
            "description": "Component owner.",
            "type": "string"
          },
          "dnsName": {
            "description": "Component DNS name",
            "type": "string"
          },
          "domain": {
            "description": "Component domain",
            "type": "string"
          },
          "description": {
            "description": "Component description",
            "type": "string"
          },
          "type": {
            "description": "Component type",
            "type": "string",
            "enum": ["backend", "library", "ui", "ui app bundle", "ui backend", "ui cdn", "config", "job"]
          },
          "framework": {
            "description": "Framework used. SpringBoot and Quarkus can automatically be detected for Java components",
            "type": "string"
          },
          "tmfSpec": {
            "description": "TMF specifications numbers",
            "type": "object",
            "patternProperties": {
              "^\\d+$": {
                "description": "TMF specification number",
                "type": "object",
                "properties": {
                  "version": {
                    "description": "TMF specification versions",
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "required": [
                  "version"
                ]
              }
            }
          },
          "language": {
            "description": "Used languages. Automatically calculated for Java and Go based components.",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "thirdparty": {
            "description": "Third party apps required for the component, anything that has its own deployment unit. Following third party apps can be automatically detected in Java components: PostgreSQL, Opensearch, Cassandra, Redis, Kafka, RabbitMQ, Zookeeper.",
            "type": "object",
            "patternProperties": {
              "^.*$": {
                "description": "App name",
                "type": "object",
                "properties": {
                  "version": {
                    "description": "App version",
                    "type": "string"
                  },
                  "mandatory": {
                    "description": "Is it optional or not. Mandatory by default.",
                    "type": "boolean"
                  }
                }
              }
            }
          },
          "dependency": {
            "description": "HTTP dependencies on other components. DNS names of dependencies shall be used",
            "type": "object",
            "properties": {
              "startup": {
                "description": "Dependencies required for the component startup",
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "mandatory": {
                "description": "Mandatory dependencies for the component",
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "optional": {
                "description": "Optional dependencies for the component",
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          },
          "queue": {
            "type": "array",
            "items" : {
              "type": "object",
              "properties": {
                "name": {
                  "description": "Queue name",
                  "type": "string"
                },
                "type": {
                  "description": "Queue type (Kafka/RabbitMQ/etc...)",
                  "type": "string"
                },
                "role": {
                  "description": "Component role for this queue",
                  "type": "string",
                  "enum": [ "producer", "consumer", "both" ]
                }
              },
              "required": [
                "name",
                "type"
              ]
            }
          },
          "database": {
            "type": "array",
            "items" : {
              "type": "object",
              "properties": {
                "name": {
                  "description": "DB name",
                  "type": "string"
                },
                "version": {
                  "description": "DB version",
                  "type": "string"
                }
              },
              "required": [
                "name"
              ]
            }
          },
          "documentation": {
            "description": "URLs to the documentation (Confluence or Git)",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "openAPI": {
            "description": "True if OpenAPI specification is provided",
            "type": "boolean"
          },
          "openAPIpublished": {
            "description": "URLs to the Git repositories where component OpenAPI specs are published",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "multitenancy": {
            "description": "Multitenancy support",
            "type": "object",
            "properties": {
              "defaultTenantId": {
                "description": "Default tenant ID support",
                "type": "boolean"
              }
            },
            "required": [
              "defaultTenantId"
            ]
          }
        },
        "required": [
          "id",
          "name",
          "dnsName",
          "type"
        ]
      }
    }
  },
  "required": [
    "name",
    "components"
  ]
}

=== exadmin/qubership-inventory-tool-cli/docs/application_inventory.json
{
    "id": "application:${app-name}:${app-version}",
    "name": "app-name",
    "version": "app-version or 'unknown'",
    "components": [ {
        "id": "component_id_1",
        "name": "microservice name",
        "owner": "owner_name",
        "dnsName": "component-1-dns-name",
        "domain": "domain-name",
        "description": "Some human-readable description",
        "type": "backend",
        "framework": "framework name and version, e.g.: 'SpringBoot 2.6.9'",
        "queue": [ {
            "name": "topic1",
            "type": "Kafka",
            "role": "producer"
        }, {
            "name": "topic2",
            "type": "RabbitMQ",
            "role": "consumer"
        }],
        "database": [ {
            "name": "PostgreSQL",
            "version": "15"
        } ],
        "language": [
            "TypeScript"
        ],
        "thirdparty": {
            "SOMETHING": {"version": ""}
        },
        "dependency": {
            "startup": [
                "component-2-dns-name"
            ],
            "mandatory": [
                "component-3-dns-name"
            ],
            "optional": [
                "component-4-dns-name",
                "component-5-dns-name"
            ]
        },
        "documentation": [
            "(URLs to the documentation (Confluence or Git))"
        ],
        "openAPI": true,
        "openAPIpublished": [
            "https://git.your.host/path/component-4/-/tree/main/component-4-spec/src/main/resources/path"
        ],
        "multitenancy": {
            "defaultTenantId": true
        }
    },
    {
        "id": "component_id_2",
        "name": "component_2_name",
        "owner": "owner_name",
        "dnsName": "component-2-dns-name",
        "domain": "domain-name",
        "description": "Some human-readable description",
        "type": "backend",
        "framework": "SpringBoot 2.6.9",
        "language": [
            "TypeScript"
        ],
        "dependency": {
            "startup": [
                "component-3-dns-name"
            ],
            "mandatory": [
                "component-4-dns-name"
            ],
            "optional": [
                "component-5-dns-name",
                "component-6-dns-name"
            ]
        },
        "documentation": [
            "(URLs to the documentation (Confluence or Git))"
        ],
        "openAPI": true,
        "openAPIpublished": [
            "https://git.your.host/path/component-5/-/tree/main/component-4-spec/src/main/resources/path"
        ],
        "multitenancy": {
            "defaultTenantId": true
        }
    } ]

}
