=== exadmin/qubership-inventory-tool-cli/docs/inventory_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "description": "Component id",
      "type": "string"
    },
    "name": {
      "description": "Component name",
      "type": "string"
    },
    "owner": {
      "description": "Component owner",
      "type": "string"
    },
    "dnsName": {
      "description": "Component DNS name",
      "type": "string",
      "pattern": "^\\S+$"
    },
    "altDnsNames":{
      "description": "Alternative DNS names in case if microservice can be deployed with various DNS names",
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^\\S+$"
      }
    },
    "domain": {
      "description": "Component domain",
      "type": "string"
    },
    "description": {
      "description": "Component description",
      "type": "string"
    },
    "type": {
      "description": "Component type",
      "type": "string",
      "enum": ["backend", "library", "ui", "ui app bundle", "ui backend", "ui cdn", "config", "job"]
    },
    "framework": {
      "description": "Framework used. SpringBoot and Quarkus can automatically be detected for Java components",
      "type": "string",
      "pattern": "^(?i)(Angular(\\s+\\S+)?|Flask(\\s+\\S+)?|Quarkus(\\s+\\S+)?|Vertx(\\s+\\S+)?|SpringBoot(\\s+\\S+)?|Drupal(\\s+\\S+)?)$"
    },
    "tmfSpec": {
      "description": "TMF specifications numbers",
      "type": "object",
      "patternProperties": {
        "^\\d+$": {
          "description": "TMF specification number",
          "type": "object",
          "properties": {
            "version": {
              "description": "TMF specification versions",
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "version"
          ]
        }
      }
    },
    "language": {
      "description": "Used languages. Automatically calculated for Java and Go based components.",
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^(?i)(C(\\+\\+|\\#)?(\\s+\\S+)?|Go(Lang)?(\\s+\\S+)?|Rust(\\s+\\S+)?|Groovy(\\s+\\S+)?|HTML(\\s+\\S+)?|Java(\\s+\\S+)?|JavaScript(\\s+\\S+)?|Lua(\\s+\\S+)?|Shell(\\s+\\S+)?|TypeScript(\\s+\\S+)?|Python(\\s+\\S+)?|PHP(\\s+\\S+)?)$"
      }
    },
    "thirdparty": {
      "description": "Third party apps required for the component, anything that has its own deployment unit. Following third party apps can be automatically detected in Java components: PostgreSQL, Opensearch, Cassandra, Redis, Kafka, RabbitMQ, Zookeeper.",
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "description": "App name",
          "type": "object",
          "properties": {
            "version": {
              "description": "App version",
              "type": "string"
            },
            "mandatory": {
              "description": "Is it optional or not. Mandatory by default.",
              "type": "boolean"
            }
          }
        }
      }
    },
    "dependency": {
      "description": "HTTP dependencies on other components. DNS names of dependencies shall be used",
      "type": "object",
      "properties": {
        "startup": {
          "description": "Dependencies required for the component startup",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "mandatory": {
          "description": "Mandatory dependencies for the component",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "optional": {
          "description": "Optional dependencies for the component",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "queue": {
      "type": "array",
      "items" : {
        "type": "object",
        "properties": {
          "name": {
            "description": "Queue name",
            "type": "string"
          },
          "type": {
            "description": "Queue type (Kafka/RabbitMQ/etc...)",
            "type": "string"
          },
          "role": {
            "description": "Component role for this queue",
            "type": "string",
            "enum": [ "producer", "consumer", "both" ]
          }
        },
        "required": [
          "name",
          "type"
        ]
      }
    },
    "database": {
      "type": "array",
      "items" : {
        "type": "object",
        "properties": {
          "name": {
            "description": "DB name",
            "type": "string"
          },
          "version": {
            "description": "DB version",
            "type": "string"
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "documentation": {
      "description": "URLs to the documentation (Confluence or Git)",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "openAPI": {
      "description": "True if OpenAPI specification is provided",
      "type": "boolean"
    },
    "openAPIpublished": {
      "description": "URLs to the Git repositories where component OpenAPI specs are published",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "multitenancy": {
      "description": "Multitenancy support",
      "type": "object",
      "properties": {
        "defaultTenantId": {
          "description": "Default tenant ID support",
          "type": "boolean"
        }
      },
      "required": [
        "defaultTenantId"
      ]
    }
  },
  "required": [
    "id",
    "name",
    "dnsName",
    "type"
  ]
}

=== exadmin/qubership-inventory-tool-cli/docs/inventory.json
{
    "id": "component-id",
    "name": "Component name",
    "owner": "Owner Name",
    "dnsName": "component-dns-name",
    "altDnsNames": ["component-alt-dns-name", "component-alt-dns-name-2"],
    "domain": "domain-name",
    "description": "Human-readable description",
    "type": "backend",
    "framework": "SpringBoot 2.6.9",
    "tmfSpec": {
        "622": {"version": ["18.0.3", "19.0.1"]},
        "666": {"version": ["18.0.3"]}
    },
    "language": [
        "TypeScript"
    ],
    "thirdparty": {
        "MongoDB": {"version": ""},
        "Redis": {"mandatory": false}
    },
    "dependency": {
        "startup": [
            "component-2-dns-name"
        ],
        "mandatory": [
            "component-3-dns-name"
        ],
        "optional": [
            "component-4-dns-name",
            "component-5-dns-name"
        ]
    },
    "documentation": [
        "(URLs to the documentation (Confluence or Git))"
    ],
    "openAPI": true,
    "openAPIpublished": ["https://git.your.host/path/component-4/-/tree/main/component-4-spec/src/main/resources/path"],
    "multitenancy": {
        "defaultTenantId": true
    }
}
